// Header - Generated by Bin2C, author 江芷酱紫.

// In file: "C:\Users\wanjiangzhi\AndroidStudioProjects\CZFH\core\app\src\main\cpp\ttf\NotoSansSC-Regular.ttf".
// Link "C:\Users\wanjiangzhi\CLionProjects\Test\cmake-build-debug\NotoSansSC-Regular.cpp".
// Written to "C:\Users\wanjiangzhi\CLionProjects\Test\cmake-build-debug\NotoSansSC-Regular.h".

#pragma once
#ifndef BIN_NotoSansSC_Regular_ttf_HEADER
#define BIN_NotoSansSC_Regular_ttf_HEADER

extern unsigned long long NotoSansSC_Regular_ttf_len; // 10560076 bits
extern unsigned long long NotoSansSC_Regular_ttf[]; // 1320009 elements

#endif // BIN_NotoSansSC_Regular_ttf_HEADER